CREATE TABLE Events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    descrizione VARCHAR(255) NULL,
    data DATETIME NOT NULL
);

CREATE TABLE Members (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    is_admin BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Partecipation (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_evento BIGINT UNSIGNED NOT NULL,
    id_partecipante BIGINT UNSIGNED NOT NULL,
    ruolo VARCHAR(255) NOT NULL,
    CONSTRAINT fk_partecipation_evento FOREIGN KEY (id_evento) REFERENCES Events(id),
    CONSTRAINT fk_partecipation_partecipante FOREIGN KEY (id_partecipante) REFERENCES Members(id),
    CONSTRAINT fk_partecipation_ruolo FOREIGN KEY (ruolo) REFERENCES Roles(nome)
);

CREATE TABLE EventRoles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_evento BIGINT UNSIGNED NOT NULL,
    nome_ruolo VARCHAR(255) NOT NULL,
    max BIGINT NOT NULL,
    CONSTRAINT fk_eventroles_evento FOREIGN KEY (id_evento) REFERENCES Events(id)
);

-- GRANT ALL PRIVILEGES ON *.* TO 'arci'@'%';
-- FLUSH PRIVILEGES;
